Repository FazeZxc/pygame-project, pull requests merged in 2024-10, with the labels that each got.

#2 #1 added oops
  index.py
Labels: gssoc-ext, hacktoberfest-accepted, level-2

#4 #3 added bullets
  index.py
Labels: gssoc-ext, hacktoberfest-accepted

#8 recent changes
  index.py
Labels: hacktoberfest-accepted

#9 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, level-3

#10 2
  assets/exit_btn.png
  assets/mountain.png
  assets/start_btn.png
  index.py
Labels: hacktoberfest-accepted

#12 4
  index.py
Labels: hacktoberfest-accepted

#13 3
  index.py
Labels: hacktoberfest-accepted
